version: "3.1"
services:
  freya:

    build: .
    restart: always
    ports:
      - "10000:10000"
    volumes:
      - freyio:/udb
      - freyio:/storage
    secrets:
      - grpc_cert
      - grpc_key
    environment:
      FREYA_CONFIG: |
        port: 10000
        storage: "/storage"
        sms:
          backend: nexmo
          endpoint: https://rest.nexmo.com/sms/json
          key: <YOUR_NEXMO_KEY>
          secret: <YOUR_NEXMO_SECRET>
        mail:
          backend: mailjet
          server: in-v3.mailjet.com
          port: 587
          email: <YOUR_EMAIL_MAIL_SERVICE>
          password: <YOUR_PASSWORD_MAIL_SERVICE>
          metadata:
            from_name: Freya
            from_email: example@example.com
secrets:
  grpc_cert:
    file: ./server-cert.crt
  grpc_key:
    file: ./server-key.key

volumes:
  freyio:
