version: "3"
services:
  freya:
    build: .
    restart: always
    ports:
      - "10000:10000"
    volumes:
      - freyio:/udb
      - freyio:/storage
    environment:
      FREYA_CONFIG: |
        port: 10000
        storage: "/storage"
        sms:
          backend: nexmo
          endpoint: https://rest.nexmo.com/sms/json
          key: <YOUR NEXMO KEY>
          secret: <YOUR NEXMO SECRET>
        mail:
          backend: mailjet
          server: in-v3.mailjet.com
          port: 587
          email: <YOUR MAILJET ACCESS EMAIL>
          password: <YOUR MAILJET ACCESS PASSWORD>
          metadata:
            from_name: Freya
            from_email: example@example.com

volumes:
  freyio:
