// Code generated by protoc-gen-go. DO NOT EDIT.
// source: freya.proto

package freya

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendEmailParams struct {
	To                   map[int32]string  `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Subject              string            `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	TemplateName         string            `protobuf:"bytes,3,opt,name=templateName,proto3" json:"templateName,omitempty"`
	TemplateFill         map[string]string `protobuf:"bytes,4,rep,name=templateFill,proto3" json:"templateFill,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SendEmailParams) Reset()         { *m = SendEmailParams{} }
func (m *SendEmailParams) String() string { return proto.CompactTextString(m) }
func (*SendEmailParams) ProtoMessage()    {}
func (*SendEmailParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{0}
}

func (m *SendEmailParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailParams.Unmarshal(m, b)
}
func (m *SendEmailParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailParams.Marshal(b, m, deterministic)
}
func (m *SendEmailParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailParams.Merge(m, src)
}
func (m *SendEmailParams) XXX_Size() int {
	return xxx_messageInfo_SendEmailParams.Size(m)
}
func (m *SendEmailParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailParams.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailParams proto.InternalMessageInfo

func (m *SendEmailParams) GetTo() map[int32]string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *SendEmailParams) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SendEmailParams) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *SendEmailParams) GetTemplateFill() map[string]string {
	if m != nil {
		return m.TemplateFill
	}
	return nil
}

type SendEmailResponse struct {
	Sended               bool     `protobuf:"varint,1,opt,name=sended,proto3" json:"sended,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailResponse) Reset()         { *m = SendEmailResponse{} }
func (m *SendEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SendEmailResponse) ProtoMessage()    {}
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{1}
}

func (m *SendEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailResponse.Unmarshal(m, b)
}
func (m *SendEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailResponse.Marshal(b, m, deterministic)
}
func (m *SendEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailResponse.Merge(m, src)
}
func (m *SendEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SendEmailResponse.Size(m)
}
func (m *SendEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailResponse proto.InternalMessageInfo

func (m *SendEmailResponse) GetSended() bool {
	if m != nil {
		return m.Sended
	}
	return false
}

func (m *SendEmailResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type TemplateData struct {
	TemplateName         string   `protobuf:"bytes,1,opt,name=templateName,proto3" json:"templateName,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateData) Reset()         { *m = TemplateData{} }
func (m *TemplateData) String() string { return proto.CompactTextString(m) }
func (*TemplateData) ProtoMessage()    {}
func (*TemplateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{2}
}

func (m *TemplateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateData.Unmarshal(m, b)
}
func (m *TemplateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateData.Marshal(b, m, deterministic)
}
func (m *TemplateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateData.Merge(m, src)
}
func (m *TemplateData) XXX_Size() int {
	return xxx_messageInfo_TemplateData.Size(m)
}
func (m *TemplateData) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateData.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateData proto.InternalMessageInfo

func (m *TemplateData) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *TemplateData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SaveTemplateResponse struct {
	Saved                bool     `protobuf:"varint,1,opt,name=saved,proto3" json:"saved,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveTemplateResponse) Reset()         { *m = SaveTemplateResponse{} }
func (m *SaveTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*SaveTemplateResponse) ProtoMessage()    {}
func (*SaveTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{3}
}

func (m *SaveTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveTemplateResponse.Unmarshal(m, b)
}
func (m *SaveTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveTemplateResponse.Marshal(b, m, deterministic)
}
func (m *SaveTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveTemplateResponse.Merge(m, src)
}
func (m *SaveTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_SaveTemplateResponse.Size(m)
}
func (m *SaveTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveTemplateResponse proto.InternalMessageInfo

func (m *SaveTemplateResponse) GetSaved() bool {
	if m != nil {
		return m.Saved
	}
	return false
}

type UpdateTemplateResponse struct {
	Updated              bool          `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	Template             *TemplateData `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	Error                *Error        `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateTemplateResponse) Reset()         { *m = UpdateTemplateResponse{} }
func (m *UpdateTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTemplateResponse) ProtoMessage()    {}
func (*UpdateTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{4}
}

func (m *UpdateTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTemplateResponse.Unmarshal(m, b)
}
func (m *UpdateTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTemplateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTemplateResponse.Merge(m, src)
}
func (m *UpdateTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTemplateResponse.Size(m)
}
func (m *UpdateTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTemplateResponse proto.InternalMessageInfo

func (m *UpdateTemplateResponse) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

func (m *UpdateTemplateResponse) GetTemplate() *TemplateData {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *UpdateTemplateResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{5}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SendEmailParams)(nil), "SendEmailParams")
	proto.RegisterMapType((map[string]string)(nil), "SendEmailParams.TemplateFillEntry")
	proto.RegisterMapType((map[int32]string)(nil), "SendEmailParams.ToEntry")
	proto.RegisterType((*SendEmailResponse)(nil), "SendEmailResponse")
	proto.RegisterType((*TemplateData)(nil), "TemplateData")
	proto.RegisterType((*SaveTemplateResponse)(nil), "SaveTemplateResponse")
	proto.RegisterType((*UpdateTemplateResponse)(nil), "UpdateTemplateResponse")
	proto.RegisterType((*Error)(nil), "Error")
}

func init() { proto.RegisterFile("freya.proto", fileDescriptor_c1a59bcae510a086) }

var fileDescriptor_c1a59bcae510a086 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x9d, 0x3a, 0x69, 0x26, 0x81, 0xb6, 0xa3, 0x50, 0x56, 0x51, 0x0f, 0xd1, 0x9e, 0x82,
	0x84, 0xf6, 0x90, 0x0a, 0x09, 0x7a, 0xe9, 0x01, 0x12, 0x89, 0x4b, 0x85, 0xb6, 0xf0, 0x00, 0x5b,
	0x3c, 0xa0, 0x80, 0x9d, 0x8d, 0xbc, 0x9b, 0xa0, 0x88, 0xc7, 0xe2, 0xc4, 0xdb, 0x21, 0xaf, 0xbd,
	0x4e, 0x1c, 0x5b, 0xe2, 0xb6, 0xdf, 0xfc, 0x7c, 0xf3, 0xcd, 0xcf, 0xc2, 0xf0, 0x5b, 0x46, 0x7b,
	0x25, 0x36, 0x99, 0xb6, 0x9a, 0xff, 0x0d, 0xe1, 0xe2, 0x91, 0xd6, 0xf1, 0x22, 0x55, 0xab, 0xe4,
	0x93, 0xca, 0x54, 0x6a, 0x70, 0x06, 0xa1, 0xd5, 0x2c, 0x98, 0x76, 0x67, 0xc3, 0x39, 0x13, 0x27,
	0x5e, 0xf1, 0x59, 0x2f, 0xd6, 0x36, 0xdb, 0xcb, 0xd0, 0x6a, 0x64, 0xd0, 0x37, 0xdb, 0xa7, 0x1f,
	0xf4, 0xd5, 0xb2, 0x70, 0x1a, 0xcc, 0x06, 0xd2, 0x43, 0xe4, 0x30, 0xb2, 0x94, 0x6e, 0x12, 0x65,
	0xe9, 0x41, 0xa5, 0xc4, 0xba, 0xce, 0x5d, 0xb3, 0xe1, 0xf2, 0x10, 0xb3, 0x5c, 0x25, 0x09, 0x3b,
	0x73, 0x15, 0x79, 0xb3, 0xe2, 0x51, 0x50, 0x51, 0xbb, 0x96, 0x37, 0x79, 0x03, 0xfd, 0x52, 0x14,
	0x5e, 0x42, 0xf7, 0x27, 0xed, 0x59, 0x30, 0x0d, 0x66, 0x91, 0xcc, 0x9f, 0x38, 0x86, 0x68, 0xa7,
	0x92, 0x2d, 0x95, 0x02, 0x0b, 0x70, 0x17, 0xbe, 0x0d, 0x26, 0xf7, 0x70, 0xd5, 0x60, 0x3e, 0x26,
	0x18, 0xfc, 0x87, 0x80, 0x7f, 0x84, 0xab, 0x4a, 0xaa, 0x24, 0xb3, 0xd1, 0x6b, 0x43, 0x78, 0x0d,
	0x3d, 0x43, 0xeb, 0x98, 0x62, 0xc7, 0x71, 0x2e, 0x4b, 0x84, 0x37, 0x10, 0x51, 0x96, 0xe9, 0xcc,
	0xd1, 0x0c, 0xe7, 0x3d, 0xb1, 0xc8, 0x91, 0x2c, 0x8c, 0x7c, 0x09, 0x23, 0xaf, 0xe5, 0x83, 0xb2,
	0xaa, 0x31, 0xbe, 0xa0, 0x65, 0x7c, 0x08, 0x67, 0xb1, 0xb2, 0xca, 0x11, 0x8e, 0xa4, 0x7b, 0xf3,
	0xd7, 0x30, 0x7e, 0x54, 0x3b, 0xf2, 0x5c, 0x95, 0xaa, 0x31, 0x44, 0x46, 0xed, 0x2a, 0x51, 0x05,
	0xe0, 0xbf, 0xe1, 0xfa, 0xcb, 0x26, 0x56, 0xb6, 0x19, 0xcf, 0xa0, 0xbf, 0x75, 0x1e, 0x9f, 0xe1,
	0x21, 0xbe, 0x82, 0x73, 0xaf, 0xa2, 0x6c, 0xe5, 0x99, 0x38, 0x96, 0x2e, 0x2b, 0xf7, 0xa1, 0xe5,
	0x6e, 0x5b, 0xcb, 0xf7, 0x10, 0x39, 0x8c, 0x37, 0x30, 0x70, 0x96, 0xf7, 0x3a, 0xa6, 0x72, 0x73,
	0x07, 0x43, 0xae, 0x24, 0x25, 0x63, 0xd4, 0x77, 0xbf, 0x00, 0x0f, 0xe7, 0x7f, 0x02, 0x88, 0x96,
	0xf9, 0x29, 0xe3, 0x3b, 0xb8, 0xc8, 0xbb, 0x7e, 0xa0, 0x5f, 0x5e, 0x09, 0xd6, 0x45, 0x4d, 0x5e,
	0x88, 0xb6, 0xb1, 0xf0, 0x0e, 0xde, 0xc1, 0xf3, 0xfa, 0x08, 0x4e, 0x33, 0x5f, 0x8a, 0xf6, 0x11,
	0xf1, 0x0e, 0xde, 0xc2, 0xa0, 0xda, 0x3f, 0x5e, 0x9e, 0x9e, 0xed, 0x04, 0x45, 0xe3, 0x3a, 0x78,
	0xe7, 0xa9, 0xe7, 0xfe, 0xdd, 0xed, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xea, 0x9e, 0x41, 0xcb,
	0x86, 0x03, 0x00, 0x00,
}
