// Code generated by protoc-gen-go. DO NOT EDIT.
// source: freyabuf/freya.proto

package freyabuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendEmailParams struct {
	To                   map[int32]string  `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Subject              string            `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	TemplateName         string            `protobuf:"bytes,3,opt,name=templateName,proto3" json:"templateName,omitempty"`
	TemplateFill         map[string]string `protobuf:"bytes,4,rep,name=templateFill,proto3" json:"templateFill,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SendEmailParams) Reset()         { *m = SendEmailParams{} }
func (m *SendEmailParams) String() string { return proto.CompactTextString(m) }
func (*SendEmailParams) ProtoMessage()    {}
func (*SendEmailParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_b84aeb77b6c87508, []int{0}
}

func (m *SendEmailParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailParams.Unmarshal(m, b)
}
func (m *SendEmailParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailParams.Marshal(b, m, deterministic)
}
func (m *SendEmailParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailParams.Merge(m, src)
}
func (m *SendEmailParams) XXX_Size() int {
	return xxx_messageInfo_SendEmailParams.Size(m)
}
func (m *SendEmailParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailParams.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailParams proto.InternalMessageInfo

func (m *SendEmailParams) GetTo() map[int32]string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *SendEmailParams) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SendEmailParams) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *SendEmailParams) GetTemplateFill() map[string]string {
	if m != nil {
		return m.TemplateFill
	}
	return nil
}

type SendEmailResponse struct {
	Sended               bool     `protobuf:"varint,1,opt,name=sended,proto3" json:"sended,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailResponse) Reset()         { *m = SendEmailResponse{} }
func (m *SendEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SendEmailResponse) ProtoMessage()    {}
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b84aeb77b6c87508, []int{1}
}

func (m *SendEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailResponse.Unmarshal(m, b)
}
func (m *SendEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailResponse.Marshal(b, m, deterministic)
}
func (m *SendEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailResponse.Merge(m, src)
}
func (m *SendEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SendEmailResponse.Size(m)
}
func (m *SendEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailResponse proto.InternalMessageInfo

func (m *SendEmailResponse) GetSended() bool {
	if m != nil {
		return m.Sended
	}
	return false
}

func (m *SendEmailResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type TemplateData struct {
	TemplateName         string   `protobuf:"bytes,1,opt,name=templateName,proto3" json:"templateName,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateData) Reset()         { *m = TemplateData{} }
func (m *TemplateData) String() string { return proto.CompactTextString(m) }
func (*TemplateData) ProtoMessage()    {}
func (*TemplateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b84aeb77b6c87508, []int{2}
}

func (m *TemplateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateData.Unmarshal(m, b)
}
func (m *TemplateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateData.Marshal(b, m, deterministic)
}
func (m *TemplateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateData.Merge(m, src)
}
func (m *TemplateData) XXX_Size() int {
	return xxx_messageInfo_TemplateData.Size(m)
}
func (m *TemplateData) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateData.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateData proto.InternalMessageInfo

func (m *TemplateData) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *TemplateData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SaveTemplateResponse struct {
	Saved                bool     `protobuf:"varint,1,opt,name=saved,proto3" json:"saved,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveTemplateResponse) Reset()         { *m = SaveTemplateResponse{} }
func (m *SaveTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*SaveTemplateResponse) ProtoMessage()    {}
func (*SaveTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b84aeb77b6c87508, []int{3}
}

func (m *SaveTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveTemplateResponse.Unmarshal(m, b)
}
func (m *SaveTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveTemplateResponse.Marshal(b, m, deterministic)
}
func (m *SaveTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveTemplateResponse.Merge(m, src)
}
func (m *SaveTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_SaveTemplateResponse.Size(m)
}
func (m *SaveTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveTemplateResponse proto.InternalMessageInfo

func (m *SaveTemplateResponse) GetSaved() bool {
	if m != nil {
		return m.Saved
	}
	return false
}

type UpdateTemplateResponse struct {
	Updated              bool          `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	Template             *TemplateData `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	Error                *Error        `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateTemplateResponse) Reset()         { *m = UpdateTemplateResponse{} }
func (m *UpdateTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTemplateResponse) ProtoMessage()    {}
func (*UpdateTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b84aeb77b6c87508, []int{4}
}

func (m *UpdateTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTemplateResponse.Unmarshal(m, b)
}
func (m *UpdateTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTemplateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTemplateResponse.Merge(m, src)
}
func (m *UpdateTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTemplateResponse.Size(m)
}
func (m *UpdateTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTemplateResponse proto.InternalMessageInfo

func (m *UpdateTemplateResponse) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

func (m *UpdateTemplateResponse) GetTemplate() *TemplateData {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *UpdateTemplateResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_b84aeb77b6c87508, []int{5}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SendEmailParams)(nil), "SendEmailParams")
	proto.RegisterMapType((map[string]string)(nil), "SendEmailParams.TemplateFillEntry")
	proto.RegisterMapType((map[int32]string)(nil), "SendEmailParams.ToEntry")
	proto.RegisterType((*SendEmailResponse)(nil), "SendEmailResponse")
	proto.RegisterType((*TemplateData)(nil), "TemplateData")
	proto.RegisterType((*SaveTemplateResponse)(nil), "SaveTemplateResponse")
	proto.RegisterType((*UpdateTemplateResponse)(nil), "UpdateTemplateResponse")
	proto.RegisterType((*Error)(nil), "Error")
}

func init() { proto.RegisterFile("freyabuf/freya.proto", fileDescriptor_b84aeb77b6c87508) }

var fileDescriptor_b84aeb77b6c87508 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x9d, 0x3a, 0x69, 0xa6, 0x81, 0xb6, 0xa3, 0x50, 0x56, 0x51, 0x0f, 0xd1, 0x9e, 0x82,
	0x84, 0x16, 0x29, 0x15, 0x12, 0xf4, 0xd2, 0x03, 0x24, 0x12, 0x97, 0x0a, 0x6d, 0xe1, 0x01, 0x36,
	0x78, 0x8a, 0x0a, 0x76, 0x36, 0xf2, 0x6e, 0x82, 0x22, 0x1e, 0x8b, 0x13, 0x6f, 0x87, 0xbc, 0xf6,
	0x3a, 0x71, 0x6c, 0x89, 0xdb, 0x7e, 0xf3, 0xf3, 0xcd, 0x37, 0x3f, 0x0b, 0xa3, 0xc7, 0x8c, 0x76,
	0x6a, 0xb9, 0x79, 0x7c, 0xe3, 0x1e, 0x62, 0x9d, 0x69, 0xab, 0xf9, 0xdf, 0x10, 0xce, 0x1f, 0x68,
	0x15, 0xcf, 0x53, 0xf5, 0x94, 0x7c, 0x56, 0x99, 0x4a, 0x0d, 0x4e, 0x21, 0xb4, 0x9a, 0x05, 0x93,
	0xee, 0xf4, 0x6c, 0xc6, 0xc4, 0x91, 0x57, 0x7c, 0xd1, 0xf3, 0x95, 0xcd, 0x76, 0x32, 0xb4, 0x1a,
	0x19, 0xf4, 0xcd, 0x66, 0xf9, 0x83, 0xbe, 0x59, 0x16, 0x4e, 0x82, 0xe9, 0x40, 0x7a, 0x88, 0x1c,
	0x86, 0x96, 0xd2, 0x75, 0xa2, 0x2c, 0xdd, 0xab, 0x94, 0x58, 0xd7, 0xb9, 0x6b, 0x36, 0x5c, 0xec,
	0x63, 0x16, 0x4f, 0x49, 0xc2, 0x4e, 0x5c, 0x45, 0xde, 0xac, 0x78, 0x10, 0x54, 0xd4, 0xae, 0xe5,
	0x8d, 0xdf, 0x42, 0xbf, 0x14, 0x85, 0x17, 0xd0, 0xfd, 0x49, 0x3b, 0x16, 0x4c, 0x82, 0x69, 0x24,
	0xf3, 0x27, 0x8e, 0x20, 0xda, 0xaa, 0x64, 0x43, 0xa5, 0xc0, 0x02, 0xdc, 0x86, 0xef, 0x82, 0xf1,
	0x1d, 0x5c, 0x36, 0x98, 0x0f, 0x09, 0x06, 0xff, 0x21, 0xe0, 0x9f, 0xe0, 0xb2, 0x92, 0x2a, 0xc9,
	0xac, 0xf5, 0xca, 0x10, 0x5e, 0x41, 0xcf, 0xd0, 0x2a, 0xa6, 0xd8, 0x71, 0x9c, 0xca, 0x12, 0xe1,
	0x35, 0x44, 0x94, 0x65, 0x3a, 0x73, 0x34, 0x67, 0xb3, 0x9e, 0x98, 0xe7, 0x48, 0x16, 0x46, 0xbe,
	0x80, 0xa1, 0xd7, 0xf2, 0x51, 0x59, 0xd5, 0x18, 0x5f, 0xd0, 0x32, 0x3e, 0x84, 0x93, 0x58, 0x59,
	0xe5, 0x08, 0x87, 0xd2, 0xbd, 0xf9, 0x6b, 0x18, 0x3d, 0xa8, 0x2d, 0x79, 0xae, 0x4a, 0xd5, 0x08,
	0x22, 0xa3, 0xb6, 0x95, 0xa8, 0x02, 0xf0, 0xdf, 0x70, 0xf5, 0x75, 0x1d, 0x2b, 0xdb, 0x8c, 0x67,
	0xd0, 0xdf, 0x38, 0x8f, 0xcf, 0xf0, 0x10, 0x5f, 0xc1, 0xa9, 0x57, 0x51, 0xb6, 0xf2, 0x4c, 0x1c,
	0x4a, 0x97, 0x95, 0x7b, 0xdf, 0x72, 0xb7, 0xad, 0xe5, 0x3b, 0x88, 0x1c, 0xc6, 0x6b, 0x18, 0x38,
	0xcb, 0x07, 0x1d, 0x53, 0xb9, 0xb9, 0xbd, 0x21, 0x57, 0x92, 0x92, 0x31, 0xea, 0xbb, 0x5f, 0x80,
	0x87, 0xb3, 0x3f, 0x01, 0x44, 0x8b, 0xfc, 0x94, 0xf1, 0x3d, 0x9c, 0xe7, 0x5d, 0xdf, 0xd3, 0x2f,
	0xaf, 0x04, 0xeb, 0xa2, 0xc6, 0x2f, 0x44, 0xdb, 0x58, 0x78, 0x07, 0x6f, 0xe1, 0x79, 0x7d, 0x04,
	0xc7, 0x99, 0x2f, 0x45, 0xfb, 0x88, 0x78, 0x07, 0x6f, 0x60, 0x50, 0xed, 0x1f, 0x2f, 0x8e, 0xcf,
	0x76, 0x8c, 0xa2, 0x71, 0x1d, 0xbc, 0xb3, 0xec, 0xb9, 0x7f, 0x77, 0xf3, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x64, 0xe5, 0x96, 0xfa, 0x8f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FreyaClient is the client API for Freya service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FreyaClient interface {
	SaveNewTemplate(ctx context.Context, in *TemplateData, opts ...grpc.CallOption) (*SaveTemplateResponse, error)
	UpdateTemplate(ctx context.Context, in *TemplateData, opts ...grpc.CallOption) (*UpdateTemplateResponse, error)
	SendEmail(ctx context.Context, in *SendEmailParams, opts ...grpc.CallOption) (*SendEmailResponse, error)
}

type freyaClient struct {
	cc *grpc.ClientConn
}

func NewFreyaClient(cc *grpc.ClientConn) FreyaClient {
	return &freyaClient{cc}
}

func (c *freyaClient) SaveNewTemplate(ctx context.Context, in *TemplateData, opts ...grpc.CallOption) (*SaveTemplateResponse, error) {
	out := new(SaveTemplateResponse)
	err := c.cc.Invoke(ctx, "/Freya/SaveNewTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freyaClient) UpdateTemplate(ctx context.Context, in *TemplateData, opts ...grpc.CallOption) (*UpdateTemplateResponse, error) {
	out := new(UpdateTemplateResponse)
	err := c.cc.Invoke(ctx, "/Freya/UpdateTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freyaClient) SendEmail(ctx context.Context, in *SendEmailParams, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, "/Freya/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FreyaServer is the server API for Freya service.
type FreyaServer interface {
	SaveNewTemplate(context.Context, *TemplateData) (*SaveTemplateResponse, error)
	UpdateTemplate(context.Context, *TemplateData) (*UpdateTemplateResponse, error)
	SendEmail(context.Context, *SendEmailParams) (*SendEmailResponse, error)
}

func RegisterFreyaServer(s *grpc.Server, srv FreyaServer) {
	s.RegisterService(&_Freya_serviceDesc, srv)
}

func _Freya_SaveNewTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreyaServer).SaveNewTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Freya/SaveNewTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreyaServer).SaveNewTemplate(ctx, req.(*TemplateData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freya_UpdateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreyaServer).UpdateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Freya/UpdateTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreyaServer).UpdateTemplate(ctx, req.(*TemplateData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freya_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreyaServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Freya/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreyaServer).SendEmail(ctx, req.(*SendEmailParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Freya_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Freya",
	HandlerType: (*FreyaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveNewTemplate",
			Handler:    _Freya_SaveNewTemplate_Handler,
		},
		{
			MethodName: "UpdateTemplate",
			Handler:    _Freya_UpdateTemplate_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _Freya_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "freyabuf/freya.proto",
}
