// Code generated by protoc-gen-go. DO NOT EDIT.
// source: freya.proto

package freya

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhoneNumber struct {
	CountryCode          string   `protobuf:"bytes,1,opt,name=CountryCode,proto3" json:"CountryCode,omitempty"`
	Number               string   `protobuf:"bytes,2,opt,name=Number,proto3" json:"Number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneNumber) Reset()         { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()    {}
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{0}
}

func (m *PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumber.Unmarshal(m, b)
}
func (m *PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumber.Merge(m, src)
}
func (m *PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_PhoneNumber.Size(m)
}
func (m *PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumber proto.InternalMessageInfo

func (m *PhoneNumber) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type SendSMSParams struct {
	Phone                *PhoneNumber      `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	TemplateName         string            `protobuf:"bytes,3,opt,name=templateName,proto3" json:"templateName,omitempty"`
	Params               map[string]string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SendSMSParams) Reset()         { *m = SendSMSParams{} }
func (m *SendSMSParams) String() string { return proto.CompactTextString(m) }
func (*SendSMSParams) ProtoMessage()    {}
func (*SendSMSParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{1}
}

func (m *SendSMSParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSMSParams.Unmarshal(m, b)
}
func (m *SendSMSParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSMSParams.Marshal(b, m, deterministic)
}
func (m *SendSMSParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSMSParams.Merge(m, src)
}
func (m *SendSMSParams) XXX_Size() int {
	return xxx_messageInfo_SendSMSParams.Size(m)
}
func (m *SendSMSParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSMSParams.DiscardUnknown(m)
}

var xxx_messageInfo_SendSMSParams proto.InternalMessageInfo

func (m *SendSMSParams) GetPhone() *PhoneNumber {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *SendSMSParams) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *SendSMSParams) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type SendSMSResponse struct {
	Sent                 bool     `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSMSResponse) Reset()         { *m = SendSMSResponse{} }
func (m *SendSMSResponse) String() string { return proto.CompactTextString(m) }
func (*SendSMSResponse) ProtoMessage()    {}
func (*SendSMSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{2}
}

func (m *SendSMSResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSMSResponse.Unmarshal(m, b)
}
func (m *SendSMSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSMSResponse.Marshal(b, m, deterministic)
}
func (m *SendSMSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSMSResponse.Merge(m, src)
}
func (m *SendSMSResponse) XXX_Size() int {
	return xxx_messageInfo_SendSMSResponse.Size(m)
}
func (m *SendSMSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSMSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendSMSResponse proto.InternalMessageInfo

func (m *SendSMSResponse) GetSent() bool {
	if m != nil {
		return m.Sent
	}
	return false
}

func (m *SendSMSResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type TemplatesList struct {
	Templates            map[string]*TemplateFields `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Error                *Error                     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TemplatesList) Reset()         { *m = TemplatesList{} }
func (m *TemplatesList) String() string { return proto.CompactTextString(m) }
func (*TemplatesList) ProtoMessage()    {}
func (*TemplatesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{3}
}

func (m *TemplatesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplatesList.Unmarshal(m, b)
}
func (m *TemplatesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplatesList.Marshal(b, m, deterministic)
}
func (m *TemplatesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplatesList.Merge(m, src)
}
func (m *TemplatesList) XXX_Size() int {
	return xxx_messageInfo_TemplatesList.Size(m)
}
func (m *TemplatesList) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplatesList.DiscardUnknown(m)
}

var xxx_messageInfo_TemplatesList proto.InternalMessageInfo

func (m *TemplatesList) GetTemplates() map[string]*TemplateFields {
	if m != nil {
		return m.Templates
	}
	return nil
}

func (m *TemplatesList) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type TemplateFields struct {
	Fields               map[string]string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TemplateFields) Reset()         { *m = TemplateFields{} }
func (m *TemplateFields) String() string { return proto.CompactTextString(m) }
func (*TemplateFields) ProtoMessage()    {}
func (*TemplateFields) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{4}
}

func (m *TemplateFields) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateFields.Unmarshal(m, b)
}
func (m *TemplateFields) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateFields.Marshal(b, m, deterministic)
}
func (m *TemplateFields) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateFields.Merge(m, src)
}
func (m *TemplateFields) XXX_Size() int {
	return xxx_messageInfo_TemplateFields.Size(m)
}
func (m *TemplateFields) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateFields.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateFields proto.InternalMessageInfo

func (m *TemplateFields) GetFields() map[string]string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type SendEmailParams struct {
	To                   map[int32]string  `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Subject              string            `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	TemplateName         string            `protobuf:"bytes,3,opt,name=templateName,proto3" json:"templateName,omitempty"`
	Params               map[string]string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SendEmailParams) Reset()         { *m = SendEmailParams{} }
func (m *SendEmailParams) String() string { return proto.CompactTextString(m) }
func (*SendEmailParams) ProtoMessage()    {}
func (*SendEmailParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{5}
}

func (m *SendEmailParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailParams.Unmarshal(m, b)
}
func (m *SendEmailParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailParams.Marshal(b, m, deterministic)
}
func (m *SendEmailParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailParams.Merge(m, src)
}
func (m *SendEmailParams) XXX_Size() int {
	return xxx_messageInfo_SendEmailParams.Size(m)
}
func (m *SendEmailParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailParams.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailParams proto.InternalMessageInfo

func (m *SendEmailParams) GetTo() map[int32]string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *SendEmailParams) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SendEmailParams) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *SendEmailParams) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type SendEmailResponse struct {
	Sent                 bool     `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailResponse) Reset()         { *m = SendEmailResponse{} }
func (m *SendEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SendEmailResponse) ProtoMessage()    {}
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{6}
}

func (m *SendEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailResponse.Unmarshal(m, b)
}
func (m *SendEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailResponse.Marshal(b, m, deterministic)
}
func (m *SendEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailResponse.Merge(m, src)
}
func (m *SendEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SendEmailResponse.Size(m)
}
func (m *SendEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailResponse proto.InternalMessageInfo

func (m *SendEmailResponse) GetSent() bool {
	if m != nil {
		return m.Sent
	}
	return false
}

func (m *SendEmailResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type TemplateData struct {
	TemplateName         string   `protobuf:"bytes,1,opt,name=templateName,proto3" json:"templateName,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateData) Reset()         { *m = TemplateData{} }
func (m *TemplateData) String() string { return proto.CompactTextString(m) }
func (*TemplateData) ProtoMessage()    {}
func (*TemplateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{7}
}

func (m *TemplateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateData.Unmarshal(m, b)
}
func (m *TemplateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateData.Marshal(b, m, deterministic)
}
func (m *TemplateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateData.Merge(m, src)
}
func (m *TemplateData) XXX_Size() int {
	return xxx_messageInfo_TemplateData.Size(m)
}
func (m *TemplateData) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateData.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateData proto.InternalMessageInfo

func (m *TemplateData) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *TemplateData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SaveTemplateResponse struct {
	Saved                bool     `protobuf:"varint,1,opt,name=saved,proto3" json:"saved,omitempty"`
	TemplateName         string   `protobuf:"bytes,2,opt,name=templateName,proto3" json:"templateName,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveTemplateResponse) Reset()         { *m = SaveTemplateResponse{} }
func (m *SaveTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*SaveTemplateResponse) ProtoMessage()    {}
func (*SaveTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{8}
}

func (m *SaveTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveTemplateResponse.Unmarshal(m, b)
}
func (m *SaveTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveTemplateResponse.Marshal(b, m, deterministic)
}
func (m *SaveTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveTemplateResponse.Merge(m, src)
}
func (m *SaveTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_SaveTemplateResponse.Size(m)
}
func (m *SaveTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveTemplateResponse proto.InternalMessageInfo

func (m *SaveTemplateResponse) GetSaved() bool {
	if m != nil {
		return m.Saved
	}
	return false
}

func (m *SaveTemplateResponse) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *SaveTemplateResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UpdateTemplateResponse struct {
	Updated              bool          `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	Template             *TemplateData `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	Error                *Error        `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateTemplateResponse) Reset()         { *m = UpdateTemplateResponse{} }
func (m *UpdateTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTemplateResponse) ProtoMessage()    {}
func (*UpdateTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{9}
}

func (m *UpdateTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTemplateResponse.Unmarshal(m, b)
}
func (m *UpdateTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTemplateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTemplateResponse.Merge(m, src)
}
func (m *UpdateTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTemplateResponse.Size(m)
}
func (m *UpdateTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTemplateResponse proto.InternalMessageInfo

func (m *UpdateTemplateResponse) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

func (m *UpdateTemplateResponse) GetTemplate() *TemplateData {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *UpdateTemplateResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a59bcae510a086, []int{10}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PhoneNumber)(nil), "freya.PhoneNumber")
	proto.RegisterType((*SendSMSParams)(nil), "freya.SendSMSParams")
	proto.RegisterMapType((map[string]string)(nil), "freya.SendSMSParams.ParamsEntry")
	proto.RegisterType((*SendSMSResponse)(nil), "freya.SendSMSResponse")
	proto.RegisterType((*TemplatesList)(nil), "freya.TemplatesList")
	proto.RegisterMapType((map[string]*TemplateFields)(nil), "freya.TemplatesList.TemplatesEntry")
	proto.RegisterType((*TemplateFields)(nil), "freya.TemplateFields")
	proto.RegisterMapType((map[string]string)(nil), "freya.TemplateFields.FieldsEntry")
	proto.RegisterType((*SendEmailParams)(nil), "freya.SendEmailParams")
	proto.RegisterMapType((map[string]string)(nil), "freya.SendEmailParams.ParamsEntry")
	proto.RegisterMapType((map[int32]string)(nil), "freya.SendEmailParams.ToEntry")
	proto.RegisterType((*SendEmailResponse)(nil), "freya.SendEmailResponse")
	proto.RegisterType((*TemplateData)(nil), "freya.TemplateData")
	proto.RegisterType((*SaveTemplateResponse)(nil), "freya.SaveTemplateResponse")
	proto.RegisterType((*UpdateTemplateResponse)(nil), "freya.UpdateTemplateResponse")
	proto.RegisterType((*Error)(nil), "freya.Error")
}

func init() { proto.RegisterFile("freya.proto", fileDescriptor_c1a59bcae510a086) }

var fileDescriptor_c1a59bcae510a086 = []byte{
	// 665 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5d, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0x9d, 0x3a, 0x69, 0xc6, 0x69, 0x0b, 0x43, 0x88, 0x2c, 0x17, 0x50, 0x30, 0x2f, 0x95,
	0x90, 0x5c, 0x29, 0x08, 0xa9, 0xed, 0x4b, 0x55, 0x95, 0xa4, 0x42, 0x40, 0x55, 0x39, 0xe5, 0x00,
	0x1b, 0xb2, 0x2d, 0x05, 0x3b, 0xb6, 0xbc, 0x9b, 0xa2, 0x5c, 0x00, 0x4e, 0xc3, 0x49, 0x78, 0x43,
	0xe2, 0x3e, 0xc8, 0xfb, 0xe3, 0x38, 0xe9, 0x56, 0x04, 0xf5, 0xc9, 0x3b, 0xb3, 0xb3, 0xdf, 0x7c,
	0xf3, 0xcd, 0x78, 0x17, 0xdc, 0xcb, 0x9c, 0xce, 0x48, 0x98, 0xe5, 0x29, 0x4f, 0xd1, 0x11, 0x86,
	0xbf, 0x73, 0x95, 0xa6, 0x57, 0x31, 0xdd, 0x13, 0xce, 0xd1, 0xf4, 0x72, 0x8f, 0x26, 0x19, 0x9f,
	0xc9, 0x98, 0xe0, 0x14, 0xdc, 0xf3, 0xcf, 0xe9, 0x84, 0x9e, 0x4d, 0x93, 0x11, 0xcd, 0xb1, 0x0b,
	0xee, 0x49, 0x3a, 0x9d, 0xf0, 0x7c, 0x76, 0x92, 0x8e, 0xa9, 0x67, 0x75, 0xad, 0xdd, 0x66, 0x54,
	0x75, 0x61, 0x07, 0xea, 0x32, 0xd6, 0xb3, 0xc5, 0xa6, 0xb2, 0x82, 0xdf, 0x16, 0x6c, 0x0e, 0xe9,
	0x64, 0x3c, 0xfc, 0x30, 0x3c, 0x27, 0x39, 0x49, 0x18, 0xee, 0x82, 0x93, 0x15, 0xd0, 0x02, 0xc5,
	0xed, 0x61, 0x28, 0xb9, 0x55, 0xd2, 0x45, 0x32, 0x00, 0x03, 0x68, 0x71, 0x9a, 0x64, 0x31, 0xe1,
	0xf4, 0x8c, 0x24, 0xd4, 0xab, 0x09, 0xe4, 0x05, 0x1f, 0xee, 0x43, 0x3d, 0x13, 0xb8, 0xde, 0x7a,
	0xb7, 0xb6, 0xeb, 0xf6, 0xba, 0x0a, 0x6e, 0x21, 0x67, 0x28, 0x3f, 0xfd, 0x82, 0x6d, 0xa4, 0xe2,
	0xfd, 0x03, 0x70, 0x2b, 0x6e, 0x7c, 0x00, 0xb5, 0xaf, 0x74, 0xa6, 0x4a, 0x2b, 0x96, 0xd8, 0x06,
	0xe7, 0x86, 0xc4, 0x53, 0xaa, 0x2a, 0x92, 0xc6, 0xa1, 0xbd, 0x6f, 0x05, 0x6f, 0x61, 0x5b, 0xe1,
	0x47, 0x94, 0x65, 0xe9, 0x84, 0x51, 0x44, 0x58, 0x67, 0x74, 0xc2, 0xc5, 0xf9, 0x8d, 0x48, 0xac,
	0x31, 0x00, 0x87, 0xe6, 0x79, 0x2a, 0x25, 0x71, 0x7b, 0x2d, 0x45, 0xad, 0x5f, 0xf8, 0x22, 0xb9,
	0x15, 0xfc, 0xb2, 0x60, 0xf3, 0x42, 0x15, 0xc4, 0xde, 0x5f, 0x33, 0x8e, 0xc7, 0xd0, 0xd4, 0x15,
	0x32, 0xcf, 0x12, 0x45, 0xbd, 0x50, 0x27, 0x17, 0x02, 0xe7, 0x96, 0xac, 0x6b, 0x7e, 0x6a, 0x95,
	0xc4, 0xfe, 0x10, 0xb6, 0x16, 0x01, 0x0c, 0x0a, 0xbc, 0xac, 0x2a, 0xe0, 0xf6, 0x1e, 0x2f, 0xd1,
	0x18, 0x5c, 0xd3, 0x78, 0xcc, 0xaa, 0xc2, 0x7c, 0xb7, 0xe6, 0xa8, 0x72, 0x17, 0x0f, 0xa0, 0x7e,
	0x29, 0x56, 0xaa, 0x96, 0xe7, 0x46, 0x90, 0x50, 0x7e, 0x54, 0x87, 0xe4, 0x81, 0xa2, 0x43, 0x15,
	0xf7, 0x7f, 0x75, 0xe8, 0xa7, 0x2d, 0x5b, 0xd4, 0x4f, 0xc8, 0x75, 0xac, 0x06, 0x2f, 0x04, 0x9b,
	0xa7, 0x8a, 0xc5, 0xb3, 0xca, 0x98, 0x54, 0x62, 0xc2, 0x8b, 0x54, 0x52, 0xb0, 0x79, 0x8a, 0x1e,
	0x34, 0xd8, 0x74, 0xf4, 0x85, 0x7e, 0xe2, 0x0a, 0x5f, 0x9b, 0x2b, 0x0d, 0xe6, 0xe1, 0xd2, 0x60,
	0x06, 0x77, 0x64, 0x34, 0x8d, 0xe6, 0x6b, 0x68, 0x28, 0x22, 0xd5, 0xa2, 0x9d, 0x7f, 0x14, 0x7d,
	0x9f, 0x89, 0x7e, 0x07, 0x0f, 0x4b, 0x62, 0xf7, 0x9e, 0xe9, 0x01, 0xb4, 0x74, 0x77, 0xdf, 0x10,
	0x4e, 0x6e, 0xc9, 0x65, 0x19, 0xe4, 0x42, 0x58, 0x1f, 0x13, 0x4e, 0x04, 0x6c, 0x2b, 0x12, 0xeb,
	0x80, 0x43, 0x7b, 0x48, 0x6e, 0xa8, 0xc6, 0x2a, 0x79, 0xb5, 0xc1, 0x61, 0xe4, 0x86, 0x8e, 0x15,
	0x31, 0x69, 0xdc, 0xca, 0x62, 0x1b, 0xb2, 0x94, 0xec, 0x6b, 0x77, 0xb3, 0xff, 0x61, 0x41, 0xe7,
	0x63, 0x36, 0x26, 0xfc, 0x76, 0x62, 0x0f, 0x1a, 0x53, 0xb1, 0xa3, 0x53, 0x6b, 0x13, 0xf7, 0x60,
	0x43, 0x27, 0x52, 0xca, 0x3c, 0x5a, 0x9a, 0xf3, 0x42, 0x89, 0xa8, 0x0c, 0x5a, 0x89, 0xc9, 0x11,
	0x38, 0xc2, 0xc6, 0x27, 0xd0, 0x14, 0x9e, 0xf2, 0xf2, 0x75, 0xa2, 0xb9, 0xa3, 0x60, 0x95, 0x50,
	0xc6, 0xc8, 0x95, 0xae, 0x59, 0x9b, 0xbd, 0x3f, 0x36, 0x38, 0x83, 0x02, 0x17, 0xfb, 0xb0, 0x5d,
	0x48, 0x79, 0x46, 0xbf, 0x69, 0x3e, 0x68, 0x22, 0xe8, 0xef, 0xe8, 0x29, 0x35, 0xe8, 0x1e, 0xac,
	0xe1, 0x00, 0xb6, 0x16, 0xa5, 0x31, 0xa3, 0x3c, 0x55, 0x4e, 0xb3, 0x8c, 0xc1, 0x1a, 0x1e, 0xc3,
	0xf6, 0x29, 0xe5, 0xc7, 0x71, 0x5c, 0x5e, 0x41, 0xd8, 0x09, 0xe5, 0x7b, 0x14, 0xea, 0xf7, 0x28,
	0xec, 0x17, 0xef, 0x91, 0xdf, 0x36, 0xdd, 0x7d, 0xc1, 0x1a, 0x1e, 0x41, 0xb3, 0x9c, 0x58, 0xec,
	0x98, 0x7f, 0x2e, 0xdf, 0x5b, 0xf6, 0x57, 0x38, 0x1c, 0x40, 0x43, 0x5d, 0xe2, 0xd8, 0x36, 0x3d,
	0x1a, 0x7e, 0x67, 0xd1, 0x3b, 0x3f, 0x3a, 0xaa, 0x0b, 0x8e, 0xaf, 0xfe, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x9b, 0x89, 0x3f, 0x6b, 0x57, 0x07, 0x00, 0x00,
}
